# Generated by Django 5.1.3 on 2024-11-28 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atendente',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('cnpj', models.CharField(max_length=14)),
                ('nome', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=15)),
                ('telefone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_medicamento', models.CharField(max_length=100)),
                ('principio_ativo', models.CharField(max_length=100)),
                ('dosagem', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('registro_anvisa', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=15)),
                ('telefone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Legislacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('requisitos', models.CharField(max_length=100)),
                ('tempo_tratamento', models.CharField(max_length=10)),
                ('validade_receituario', models.CharField(max_length=10)),
                ('intercambialidade_med', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_medicamento', models.CharField(max_length=100)),
                ('principio_ativo', models.CharField(max_length=100)),
                ('dosagem', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('fabricante', models.CharField(max_length=20)),
                ('legislacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.legislacao')),
            ],
        ),
        migrations.CreateModel(
            name='ClienteMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medicamento')),
            ],
            options={
                'unique_together': {('cliente', 'medicamento')},
            },
        ),
        migrations.CreateModel(
            name='AtendenteMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.atendente')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medicamento')),
            ],
            options={
                'unique_together': {('atendente', 'medicamento')},
            },
        ),
    ]
