# Generated by Django 5.1.3 on 2024-11-29 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='medicamento',
            options={'ordering': ['nome_medicamento']},
        ),
        migrations.AlterField(
            model_name='legislacao',
            name='requisitos',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='LogAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=255)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.AlterField(
            model_name='atendentemedicamento',
            name='atendente',
            field=models.ForeignKey(limit_choices_to={'cnpj__isnull': False}, on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
        migrations.AlterField(
            model_name='clientemedicamento',
            name='cliente',
            field=models.ForeignKey(limit_choices_to={'cnpj': ''}, on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
        migrations.DeleteModel(
            name='Atendente',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
