# Generated by Django 5.1.3 on 2024-12-01 04:51

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_atendente_cliente_remove_usuario_telefone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoRedefinicaoSenha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('data_geracao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_expiracao', models.DateTimeField(default=datetime.datetime(2024, 12, 1, 5, 51, 36, 326632, tzinfo=datetime.timezone.utc))),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
    ]
