# Generated by Django 5.1.3 on 2024-12-01 04:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_codigoredefinicaosenha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigoredefinicaosenha',
            name='data_expiracao',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 1, 5, 57, 55, 786683, tzinfo=datetime.timezone.utc)),
        ),
    ]
